version: '3.8'
services:
  db:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wendy
      POSTGRES_PASSWORD: wendy
      POSTGRES_DB: paymentdb
    ports:
      - "5300:5432"
    networks:
      - my_network

  pgadmin:
    container_name: pgAdmin4-container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
